name: Module - Documentation
on: workflow_call

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Generate Documentation
        run: |
          doxygen Doxyfile
          mkdir -p documentation/static/api
          cp -r docs_output/html/. documentation/static/api/

      # 2. Build Docusaurus
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Build Site
        working-directory: ./documentation
        env:
          DOCS_BASE_URL: ${{ vars.DOCS_BASE_URL }}
        run: |
          npm ci
          npm run build

      # 3. Deploy
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/build
          publish_branch: gh-pages
