name: Publish Release

on:
  push:
    tags:
      - "v*"

jobs:
  create_release:
    name: Create Release & Upload Asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Binary (Release Mode)
        run: |
          make re DEBUG=0
          
      - name: Package Binary
        run: |
          tar -czvf pbrain-gomoku-ai-linux-x86_64.tar.gz pbrain-gomoku-ai README.md
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pbrain-gomoku-ai-linux-x86_64.tar.gz
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}